"""
Comprehensive Master Product Catalog for Quick Commerce (Blinkit & Zepto)
Contains 115+ high-demand daily essential products across 10 core categories with accurate pricing and high-res images.
"""

from typing import List, Dict, Any

CATEGORIES = [
    {"id": "all", "name": "All Products", "icon": "🔥"},
    {"id": "dairy", "name": "Dairy & Breakfast", "icon": "🥛"},
    {"id": "fruits_veg", "name": "Fresh Fruits & Veggies", "icon": "🍎"},
    {"id": "bakery", "name": "Bread, Eggs & Bakery", "icon": "🍞"},
    {"id": "snacks", "name": "Snacks & Munchies", "icon": "🍿"},
    {"id": "drinks", "name": "Cold Drinks & Juices", "icon": "🥤"},
    {"id": "staples", "name": "Atta, Rice, Dal & Oil", "icon": "🍚"},
    {"id": "sweets", "name": "Chocolates & Sweets", "icon": "🍫"},
    {"id": "tea_coffee", "name": "Tea, Coffee & Health", "icon": "☕"},
    {"id": "cleaning", "name": "Cleaning & Household", "icon": "🧹"},
    {"id": "personal_care", "name": "Personal Care", "icon": "✨"},
]

MASTER_PRODUCTS: List[Dict[str, Any]] = [
    # -------------------------------------------------------------------------
    # 1. DAIRY & BREAKFAST (15 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_dairy_01",
        "category": "dairy",
        "title": "Amul Taaza Toned Fresh Milk",
        "packSize": "500 ml",
        "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk", "dairy", "amul", "taaza", "toned", "fresh"],
        "blinkit": {"price": 30.0, "mrp": 30.0, "eta": "12 mins", "deepLink": "https://blinkit.com/prn/amul-taaza-toned-fresh-milk/prid/19512"},
        "zepto": {"price": 29.0, "mrp": 30.0, "eta": "9 mins", "deepLink": "https://zeptonow.com/pn/amul-taaza-milk/pvid/123"},
    },
    {
        "id": "prod_dairy_02",
        "category": "dairy",
        "title": "Amul Gold Full Cream Fresh Milk",
        "packSize": "500 ml",
        "imageUrl": "https://images.unsplash.com/photo-1528750997573-59b89d56f4f7?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk", "dairy", "amul", "gold", "full cream"],
        "blinkit": {"price": 36.0, "mrp": 36.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 35.0, "mrp": 36.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_03",
        "category": "dairy",
        "title": "Nandini Toned Fresh Milk",
        "packSize": "500 ml",
        "imageUrl": "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk", "dairy", "nandini", "toned", "fresh"],
        "blinkit": {"price": 24.0, "mrp": 24.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 24.0, "mrp": 24.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_04",
        "category": "dairy",
        "title": "Mother Dairy Full Cream Milk",
        "packSize": "500 ml",
        "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk", "dairy", "mother dairy", "full cream"],
        "blinkit": {"price": 33.0, "mrp": 34.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 33.0, "mrp": 34.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_05",
        "category": "dairy",
        "title": "Amul Pasteurized Salted Butter",
        "packSize": "100 g",
        "imageUrl": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=300&auto=format&fit=crop&q=80",
        "tags": ["butter", "dairy", "amul", "salted butter", "makhan"],
        "blinkit": {"price": 58.0, "mrp": 60.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 57.0, "mrp": 60.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_06",
        "category": "dairy",
        "title": "Amul Pasteurized Salted Butter",
        "packSize": "500 g",
        "imageUrl": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=300&auto=format&fit=crop&q=80",
        "tags": ["butter", "dairy", "amul", "500g", "makhan"],
        "blinkit": {"price": 275.0, "mrp": 285.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 272.0, "mrp": 285.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_07",
        "category": "dairy",
        "title": "Mother Dairy Classic Dahi / Curd",
        "packSize": "400 g",
        "imageUrl": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300&auto=format&fit=crop&q=80",
        "tags": ["curd", "dahi", "dairy", "mother dairy", "yogurt"],
        "blinkit": {"price": 35.0, "mrp": 35.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 34.0, "mrp": 35.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_08",
        "category": "dairy",
        "title": "Amul Fresh Malai Paneer",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300&auto=format&fit=crop&q=80",
        "tags": ["paneer", "dairy", "amul", "malai paneer", "cottage cheese"],
        "blinkit": {"price": 90.0, "mrp": 95.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 88.0, "mrp": 95.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_09",
        "category": "dairy",
        "title": "Milky Mist Paneer Premium Block",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300&auto=format&fit=crop&q=80",
        "tags": ["paneer", "milky mist", "cottage cheese", "dairy"],
        "blinkit": {"price": 95.0, "mrp": 105.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 92.0, "mrp": 105.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_10",
        "category": "dairy",
        "title": "Amul Processed Cheese Slices",
        "packSize": "200 g (10 Slices)",
        "imageUrl": "https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=300&auto=format&fit=crop&q=80",
        "tags": ["cheese", "slices", "amul", "dairy", "cheese slices"],
        "blinkit": {"price": 140.0, "mrp": 145.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 136.0, "mrp": 145.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_11",
        "category": "dairy",
        "title": "Britannia Processed Cheese Block",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=300&auto=format&fit=crop&q=80",
        "tags": ["cheese", "britannia", "block", "dairy"],
        "blinkit": {"price": 145.0, "mrp": 155.0, "eta": "13 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 140.0, "mrp": 155.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_12",
        "category": "dairy",
        "title": "Epigamia Greek Yogurt Strawberry",
        "packSize": "90 g Cup",
        "imageUrl": "https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=300&auto=format&fit=crop&q=80",
        "tags": ["yogurt", "epigamia", "greek yogurt", "strawberry", "curd"],
        "blinkit": {"price": 48.0, "mrp": 50.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 45.0, "mrp": 50.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_13",
        "category": "dairy",
        "title": "Nestle Everyday Dairy Whitener",
        "packSize": "400 g Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk powder", "dairy whitener", "nestle", "everyday", "tea milk"],
        "blinkit": {"price": 240.0, "mrp": 260.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 235.0, "mrp": 260.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_14",
        "category": "dairy",
        "title": "Amul Fresh Cream Tetrapack",
        "packSize": "250 ml",
        "imageUrl": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80",
        "tags": ["cream", "fresh cream", "amul", "malai"],
        "blinkit": {"price": 68.0, "mrp": 70.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 67.0, "mrp": 70.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_dairy_15",
        "category": "dairy",
        "title": "Country Delight Pure Cow Milk",
        "packSize": "500 ml",
        "imageUrl": "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300&auto=format&fit=crop&q=80",
        "tags": ["milk", "cow milk", "country delight", "dairy"],
        "blinkit": {"price": 42.0, "mrp": 45.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 40.0, "mrp": 45.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 2. FRESH FRUITS & VEGETABLES (15 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_veg_01",
        "category": "fruits_veg",
        "title": "Fresh Hybrid Tomato",
        "packSize": "500 g",
        "imageUrl": "https://images.unsplash.com/photo-1546470427-227c7369a92f?w=300&auto=format&fit=crop&q=80",
        "tags": ["tomato", "tamatar", "vegetables", "fresh", "veggies"],
        "blinkit": {"price": 22.0, "mrp": 28.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 20.0, "mrp": 28.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_02",
        "category": "fruits_veg",
        "title": "Fresh Red Onion / Pyaz",
        "packSize": "1 kg",
        "imageUrl": "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=300&auto=format&fit=crop&q=80",
        "tags": ["onion", "pyaz", "vegetables", "fresh", "veggies"],
        "blinkit": {"price": 38.0, "mrp": 45.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 35.0, "mrp": 45.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_03",
        "category": "fruits_veg",
        "title": "Fresh Potato / Aloo",
        "packSize": "1 kg",
        "imageUrl": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&auto=format&fit=crop&q=80",
        "tags": ["potato", "aloo", "vegetables", "fresh", "veggies"],
        "blinkit": {"price": 30.0, "mrp": 35.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 28.0, "mrp": 35.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_04",
        "category": "fruits_veg",
        "title": "Fresh Coriander Leaves / Dhaniya",
        "packSize": "100 g Bunch",
        "imageUrl": "https://images.unsplash.com/photo-1588879462719-75e7a9b0c797?w=300&auto=format&fit=crop&q=80",
        "tags": ["coriander", "dhaniya", "herb", "vegetables", "fresh"],
        "blinkit": {"price": 12.0, "mrp": 15.0, "eta": "8 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 10.0, "mrp": 15.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_05",
        "category": "fruits_veg",
        "title": "Fresh Ginger / Adrak",
        "packSize": "100 g",
        "imageUrl": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=300&auto=format&fit=crop&q=80",
        "tags": ["ginger", "adrak", "vegetables", "fresh", "spices"],
        "blinkit": {"price": 18.0, "mrp": 22.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 16.0, "mrp": 22.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_06",
        "category": "fruits_veg",
        "title": "Fresh Green Chillies / Hari Mirch",
        "packSize": "100 g",
        "imageUrl": "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=300&auto=format&fit=crop&q=80",
        "tags": ["chilli", "mirch", "green chilli", "vegetables", "fresh"],
        "blinkit": {"price": 14.0, "mrp": 18.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 12.0, "mrp": 18.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_07",
        "category": "fruits_veg",
        "title": "Fresh Lemon / Nimbu",
        "packSize": "4 pcs",
        "imageUrl": "https://images.unsplash.com/photo-1533082603883-3be20557bd41?w=300&auto=format&fit=crop&q=80",
        "tags": ["lemon", "nimbu", "citrus", "fresh", "vegetables"],
        "blinkit": {"price": 20.0, "mrp": 25.0, "eta": "8 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 18.0, "mrp": 25.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_08",
        "category": "fruits_veg",
        "title": "Fresh Green Capsicum / Shimla Mirch",
        "packSize": "250 g",
        "imageUrl": "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=300&auto=format&fit=crop&q=80",
        "tags": ["capsicum", "shimla mirch", "peppers", "vegetables", "fresh"],
        "blinkit": {"price": 25.0, "mrp": 30.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 22.0, "mrp": 30.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_09",
        "category": "fruits_veg",
        "title": "Fresh English Cucumber / Kheera",
        "packSize": "500 g",
        "imageUrl": "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=300&auto=format&fit=crop&q=80",
        "tags": ["cucumber", "kheera", "salad", "vegetables", "fresh"],
        "blinkit": {"price": 24.0, "mrp": 30.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 22.0, "mrp": 30.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_veg_10",
        "category": "fruits_veg",
        "title": "Fresh Orange Carrots / Gajar",
        "packSize": "500 g",
        "imageUrl": "https://images.unsplash.com/photo-1598170845058-32b9d6a5c317?w=300&auto=format&fit=crop&q=80",
        "tags": ["carrot", "gajar", "vegetables", "fresh", "salad"],
        "blinkit": {"price": 28.0, "mrp": 35.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 25.0, "mrp": 35.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_fruit_01",
        "category": "fruits_veg",
        "title": "Fresh Robusta Bananas",
        "packSize": "500 g (4-5 pcs)",
        "imageUrl": "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=300&auto=format&fit=crop&q=80",
        "tags": ["banana", "kela", "fruits", "fresh", "robusta"],
        "blinkit": {"price": 32.0, "mrp": 38.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 29.0, "mrp": 38.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_fruit_02",
        "category": "fruits_veg",
        "title": "Fresh Royal Gala Apples",
        "packSize": "4 pcs (500 g)",
        "imageUrl": "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=300&auto=format&fit=crop&q=80",
        "tags": ["apple", "seb", "fruits", "gala apple", "fresh"],
        "blinkit": {"price": 110.0, "mrp": 130.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 105.0, "mrp": 130.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_fruit_03",
        "category": "fruits_veg",
        "title": "Fresh Sweet Nagpur Oranges",
        "packSize": "1 kg",
        "imageUrl": "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=300&auto=format&fit=crop&q=80",
        "tags": ["orange", "santra", "citrus", "fruits", "fresh"],
        "blinkit": {"price": 75.0, "mrp": 90.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 70.0, "mrp": 90.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_fruit_04",
        "category": "fruits_veg",
        "title": "Fresh Semi-Ripe Papaya",
        "packSize": "1 pc (~800 g)",
        "imageUrl": "https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=300&auto=format&fit=crop&q=80",
        "tags": ["papaya", "papita", "fruits", "fresh"],
        "blinkit": {"price": 45.0, "mrp": 55.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 42.0, "mrp": 55.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_fruit_05",
        "category": "fruits_veg",
        "title": "Fresh Ruby Pomegranate / Anar",
        "packSize": "2 pcs (400 g)",
        "imageUrl": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=300&auto=format&fit=crop&q=80",
        "tags": ["pomegranate", "anar", "fruits", "fresh"],
        "blinkit": {"price": 120.0, "mrp": 140.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 115.0, "mrp": 140.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 3. BREAD, EGGS & BAKERY (12 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_bakery_01",
        "category": "bakery",
        "title": "Modern White Sandwich Bread",
        "packSize": "400 g",
        "imageUrl": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=80",
        "tags": ["bread", "bakery", "modern", "white bread", "sandwich"],
        "blinkit": {"price": 42.0, "mrp": 45.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 40.0, "mrp": 45.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_02",
        "category": "bakery",
        "title": "Harvest Gold 100% Atta Whole Wheat Bread",
        "packSize": "400 g",
        "imageUrl": "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=300&auto=format&fit=crop&q=80",
        "tags": ["bread", "atta", "wheat", "harvest gold", "brown bread"],
        "blinkit": {"price": 55.0, "mrp": 55.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 54.0, "mrp": 55.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_03",
        "category": "bakery",
        "title": "English Oven Sandwich White Bread",
        "packSize": "400 g",
        "imageUrl": "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=300&auto=format&fit=crop&q=80",
        "tags": ["bread", "english oven", "sandwich", "white"],
        "blinkit": {"price": 48.0, "mrp": 50.0, "eta": "15 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 47.0, "mrp": 50.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_04",
        "category": "bakery",
        "title": "Bonn Soft Pav / Burger Buns",
        "packSize": "Pack of 6",
        "imageUrl": "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=300&auto=format&fit=crop&q=80",
        "tags": ["pav", "buns", "burger", "bakery", "bonn"],
        "blinkit": {"price": 32.0, "mrp": 35.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 30.0, "mrp": 35.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_05",
        "category": "bakery",
        "title": "Eggoz Farm Fresh White Eggs",
        "packSize": "6 pcs",
        "imageUrl": "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=300&auto=format&fit=crop&q=80",
        "tags": ["egg", "eggs", "eggoz", "poultry", "breakfast"],
        "blinkit": {"price": 54.0, "mrp": 60.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 51.0, "mrp": 60.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_06",
        "category": "bakery",
        "title": "Eggoz Farm Fresh White Eggs (Crate)",
        "packSize": "12 pcs",
        "imageUrl": "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=300&auto=format&fit=crop&q=80",
        "tags": ["egg", "eggs", "12 eggs", "eggoz", "poultry"],
        "blinkit": {"price": 105.0, "mrp": 120.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 99.0, "mrp": 120.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_07",
        "category": "bakery",
        "title": "Hen Fruit Fresh Farm White Eggs",
        "packSize": "6 pcs",
        "imageUrl": "https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?w=300&auto=format&fit=crop&q=80",
        "tags": ["egg", "eggs", "hen fruit", "farm fresh"],
        "blinkit": {"price": 52.0, "mrp": 58.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 50.0, "mrp": 58.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_08",
        "category": "bakery",
        "title": "Britannia Good Day Butter Cookies",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300&auto=format&fit=crop&q=80",
        "tags": ["biscuit", "cookies", "good day", "britannia", "butter cookies"],
        "blinkit": {"price": 40.0, "mrp": 45.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 38.0, "mrp": 45.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_09",
        "category": "bakery",
        "title": "Oreo Original Chocolate Sandwich Biscuits",
        "packSize": "120 g",
        "imageUrl": "https://images.unsplash.com/photo-1568051243851-f9b136146e97?w=300&auto=format&fit=crop&q=80",
        "tags": ["biscuit", "oreo", "chocolate", "cookies", "cadbury"],
        "blinkit": {"price": 35.0, "mrp": 40.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 34.0, "mrp": 40.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_10",
        "category": "bakery",
        "title": "Parle-G Gold Glucose Biscuits",
        "packSize": "1 kg Mega Pack",
        "imageUrl": "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=300&auto=format&fit=crop&q=80",
        "tags": ["parle g", "biscuits", "glucose", "chai biscuit"],
        "blinkit": {"price": 115.0, "mrp": 130.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 110.0, "mrp": 130.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_11",
        "category": "bakery",
        "title": "Hide & Seek Chocolate Chip Cookies",
        "packSize": "120 g",
        "imageUrl": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=300&auto=format&fit=crop&q=80",
        "tags": ["hide and seek", "choco chip", "cookies", "parle"],
        "blinkit": {"price": 45.0, "mrp": 50.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 42.0, "mrp": 50.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_bakery_12",
        "category": "bakery",
        "title": "Sunfeast Dark Fantasy Choco Fills",
        "packSize": "300 g",
        "imageUrl": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=300&auto=format&fit=crop&q=80",
        "tags": ["dark fantasy", "choco fills", "cookies", "sunfeast", "biscuit"],
        "blinkit": {"price": 135.0, "mrp": 160.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 129.0, "mrp": 160.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 4. SNACKS, MUNCHIES & INSTANT FOOD (14 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_snack_01",
        "category": "snacks",
        "title": "Lay's India's Magic Masala Potato Chips",
        "packSize": "50 g",
        "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&auto=format&fit=crop&q=80",
        "tags": ["chips", "lays", "magic masala", "snacks", "crisps"],
        "blinkit": {"price": 20.0, "mrp": 20.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 19.0, "mrp": 20.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_02",
        "category": "snacks",
        "title": "Lay's Spanish Tomato Tango Chips",
        "packSize": "50 g",
        "imageUrl": "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?w=300&auto=format&fit=crop&q=80",
        "tags": ["chips", "lays", "tomato tango", "snacks"],
        "blinkit": {"price": 20.0, "mrp": 20.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 19.0, "mrp": 20.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_03",
        "category": "snacks",
        "title": "Lay's Classic Salted Potato Chips",
        "packSize": "50 g",
        "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&auto=format&fit=crop&q=80",
        "tags": ["chips", "lays", "salted", "classic salted"],
        "blinkit": {"price": 20.0, "mrp": 20.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 19.0, "mrp": 20.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_04",
        "category": "snacks",
        "title": "Kurkure Masala Munch Namkeen",
        "packSize": "85 g",
        "imageUrl": "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=300&auto=format&fit=crop&q=80",
        "tags": ["kurkure", "masala munch", "namkeen", "snacks", "tedhe medhe"],
        "blinkit": {"price": 20.0, "mrp": 20.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 19.5, "mrp": 20.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_05",
        "category": "snacks",
        "title": "Doritos Cheese Supreme Nachos",
        "packSize": "60 g",
        "imageUrl": "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=300&auto=format&fit=crop&q=80",
        "tags": ["doritos", "nachos", "cheese", "tortilla chips", "snacks"],
        "blinkit": {"price": 30.0, "mrp": 30.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 28.0, "mrp": 30.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_06",
        "category": "snacks",
        "title": "Pringles Sour Cream & Onion Potato Crisps",
        "packSize": "107 g Can",
        "imageUrl": "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&auto=format&fit=crop&q=80",
        "tags": ["pringles", "sour cream", "onion", "crisps", "can"],
        "blinkit": {"price": 105.0, "mrp": 115.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 99.0, "mrp": 115.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_07",
        "category": "snacks",
        "title": "Haldiram's Nagpur Aloo Bhujia",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80",
        "tags": ["haldiram", "aloo bhujia", "bhujia", "namkeen", "snacks"],
        "blinkit": {"price": 55.0, "mrp": 60.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 52.0, "mrp": 60.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_08",
        "category": "snacks",
        "title": "Haldiram's Khatta Meetha Namkeen",
        "packSize": "200 g",
        "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80",
        "tags": ["haldiram", "khatta meetha", "namkeen", "mixture"],
        "blinkit": {"price": 52.0, "mrp": 58.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 49.0, "mrp": 58.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_09",
        "category": "snacks",
        "title": "Maggi 2-Minute Masala Instant Noodles",
        "packSize": "Pack of 4 (280 g)",
        "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=300&auto=format&fit=crop&q=80",
        "tags": ["maggi", "noodles", "instant noodles", "masala", "nestle"],
        "blinkit": {"price": 58.0, "mrp": 60.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 56.0, "mrp": 60.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_10",
        "category": "snacks",
        "title": "Maggi 2-Minute Masala Noodles (Mega Pack)",
        "packSize": "Pack of 8 (560 g)",
        "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=300&auto=format&fit=crop&q=80",
        "tags": ["maggi", "noodles", "pack of 8", "snacks", "family pack"],
        "blinkit": {"price": 112.0, "mrp": 120.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 108.0, "mrp": 120.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_11",
        "category": "snacks",
        "title": "Sunfeast Yippee Magic Masala Noodles",
        "packSize": "Pack of 4 (240 g)",
        "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=300&auto=format&fit=crop&q=80",
        "tags": ["yippee", "noodles", "masala", "sunfeast"],
        "blinkit": {"price": 52.0, "mrp": 56.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 50.0, "mrp": 56.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_12",
        "category": "snacks",
        "title": "Act II Golden Sizzle Butter Popcorn",
        "packSize": "150 g Pack",
        "imageUrl": "https://images.unsplash.com/photo-1578849278619-e73505e9610f?w=300&auto=format&fit=crop&q=80",
        "tags": ["popcorn", "act ii", "butter popcorn", "snacks", "movie snack"],
        "blinkit": {"price": 40.0, "mrp": 45.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 38.0, "mrp": 45.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_13",
        "category": "snacks",
        "title": "Haldiram's Minute Khana Punjabi Samosa",
        "packSize": "8 pcs (320 g)",
        "imageUrl": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300&auto=format&fit=crop&q=80",
        "tags": ["samosa", "haldiram", "frozen", "snacks", "punjabi samosa"],
        "blinkit": {"price": 140.0, "mrp": 160.0, "eta": "13 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 134.0, "mrp": 160.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_snack_14",
        "category": "snacks",
        "title": "McCain French Fries Crispy",
        "packSize": "420 g Pack",
        "imageUrl": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300&auto=format&fit=crop&q=80",
        "tags": ["french fries", "mccain", "fries", "frozen snacks", "potato fries"],
        "blinkit": {"price": 125.0, "mrp": 145.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 118.0, "mrp": 145.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 5. COLD DRINKS, JUICES & BEVERAGES (12 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_drink_01",
        "category": "drinks",
        "title": "Coca-Cola Original Taste Soft Drink",
        "packSize": "750 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&auto=format&fit=crop&q=80",
        "tags": ["coke", "coca cola", "cold drink", "soda", "beverage"],
        "blinkit": {"price": 40.0, "mrp": 40.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 38.0, "mrp": 40.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_02",
        "category": "drinks",
        "title": "Thums Up Charged Soft Drink",
        "packSize": "750 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=300&auto=format&fit=crop&q=80",
        "tags": ["thums up", "coke", "cola", "cold drink", "beverage"],
        "blinkit": {"price": 40.0, "mrp": 40.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 39.0, "mrp": 40.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_03",
        "category": "drinks",
        "title": "Sprite Lemon Lime Cold Drink",
        "packSize": "750 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=300&auto=format&fit=crop&q=80",
        "tags": ["sprite", "lemon", "lime", "cold drink", "soda"],
        "blinkit": {"price": 40.0, "mrp": 40.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 38.0, "mrp": 40.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_04",
        "category": "drinks",
        "title": "Pepsi Cola Carbonated Soft Drink",
        "packSize": "750 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=80",
        "tags": ["pepsi", "cola", "cold drink", "beverage"],
        "blinkit": {"price": 40.0, "mrp": 40.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 38.0, "mrp": 40.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_05",
        "category": "drinks",
        "title": "Red Bull Energy Drink Can",
        "packSize": "250 ml Can",
        "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=80",
        "tags": ["red bull", "energy drink", "can", "beverage", "energy"],
        "blinkit": {"price": 125.0, "mrp": 125.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 119.0, "mrp": 125.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_06",
        "category": "drinks",
        "title": "Monster Energy Drink Can",
        "packSize": "350 ml Can",
        "imageUrl": "https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=300&auto=format&fit=crop&q=80",
        "tags": ["monster", "energy drink", "beverage", "can"],
        "blinkit": {"price": 120.0, "mrp": 125.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 115.0, "mrp": 125.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_07",
        "category": "drinks",
        "title": "Real Fruit Power Mixed Fruit Juice",
        "packSize": "1 L Tetrapack",
        "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=300&auto=format&fit=crop&q=80",
        "tags": ["juice", "real", "mixed fruit", "beverage", "dabur"],
        "blinkit": {"price": 115.0, "mrp": 130.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 109.0, "mrp": 130.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_08",
        "category": "drinks",
        "title": "Tropicana 100% Orange Delight Juice",
        "packSize": "1 L Tetrapack",
        "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=300&auto=format&fit=crop&q=80",
        "tags": ["orange juice", "tropicana", "juice", "fruit juice"],
        "blinkit": {"price": 120.0, "mrp": 135.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 114.0, "mrp": 135.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_09",
        "category": "drinks",
        "title": "Frooti Fresh Mango Drink",
        "packSize": "1.2 L Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1546173159-315724a31696?w=300&auto=format&fit=crop&q=80",
        "tags": ["frooti", "mango", "mango drink", "parle agro"],
        "blinkit": {"price": 65.0, "mrp": 75.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 62.0, "mrp": 75.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_10",
        "category": "drinks",
        "title": "Maaza Real Mango Drink",
        "packSize": "1.2 L Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1546173159-315724a31696?w=300&auto=format&fit=crop&q=80",
        "tags": ["maaza", "mango", "mango juice", "beverage"],
        "blinkit": {"price": 68.0, "mrp": 75.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 64.0, "mrp": 75.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_11",
        "category": "drinks",
        "title": "Bisleri Packaged Mineral Water",
        "packSize": "1 L Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=300&auto=format&fit=crop&q=80",
        "tags": ["water", "mineral water", "bisleri", "bottle"],
        "blinkit": {"price": 20.0, "mrp": 20.0, "eta": "8 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 20.0, "mrp": 20.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_drink_12",
        "category": "drinks",
        "title": "Schweppes Tonic Water Can",
        "packSize": "300 ml Can",
        "imageUrl": "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=300&auto=format&fit=crop&q=80",
        "tags": ["tonic water", "schweppes", "soda", "mixer"],
        "blinkit": {"price": 50.0, "mrp": 50.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 48.0, "mrp": 50.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 6. ATTA, RICE, DAL & OIL (14 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_staple_01",
        "category": "staples",
        "title": "Aashirvaad Superior MP Chakki Atta",
        "packSize": "5 kg Bag",
        "imageUrl": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=300&auto=format&fit=crop&q=80",
        "tags": ["atta", "flour", "wheat", "aashirvaad", "staples", "gehu"],
        "blinkit": {"price": 245.0, "mrp": 265.0, "eta": "15 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 240.0, "mrp": 265.0, "eta": "12 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_02",
        "category": "staples",
        "title": "Aashirvaad Superior MP Chakki Atta",
        "packSize": "10 kg Bag",
        "imageUrl": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=300&auto=format&fit=crop&q=80",
        "tags": ["atta", "flour", "10kg", "aashirvaad", "wheat"],
        "blinkit": {"price": 475.0, "mrp": 520.0, "eta": "18 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 465.0, "mrp": 520.0, "eta": "14 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_03",
        "category": "staples",
        "title": "Fortune Chakki Fresh Atta",
        "packSize": "5 kg Bag",
        "imageUrl": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=300&auto=format&fit=crop&q=80",
        "tags": ["atta", "fortune", "flour", "wheat", "chakki"],
        "blinkit": {"price": 230.0, "mrp": 250.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 228.0, "mrp": 250.0, "eta": "11 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_04",
        "category": "staples",
        "title": "Daawat Rozana Super Basmati Rice",
        "packSize": "5 kg Bag",
        "imageUrl": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80",
        "tags": ["rice", "chawal", "basmati", "daawat", "staples"],
        "blinkit": {"price": 380.0, "mrp": 450.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 369.0, "mrp": 450.0, "eta": "11 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_05",
        "category": "staples",
        "title": "India Gate Super Basmati Rice",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=80",
        "tags": ["rice", "india gate", "basmati", "biryani rice"],
        "blinkit": {"price": 140.0, "mrp": 165.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 135.0, "mrp": 165.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_06",
        "category": "staples",
        "title": "Tata Sampann Unpolished Toor Dal",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=300&auto=format&fit=crop&q=80",
        "tags": ["toor dal", "dal", "tata sampann", "pulses", "arhar dal"],
        "blinkit": {"price": 185.0, "mrp": 205.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 179.0, "mrp": 205.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_07",
        "category": "staples",
        "title": "Tata Sampann Unpolished Moong Dal",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=300&auto=format&fit=crop&q=80",
        "tags": ["moong dal", "dal", "tata sampann", "yellow dal"],
        "blinkit": {"price": 165.0, "mrp": 185.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 159.0, "mrp": 185.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_08",
        "category": "staples",
        "title": "Tata Sampann Premium Chana Dal",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=300&auto=format&fit=crop&q=80",
        "tags": ["chana dal", "dal", "tata sampann", "pulses"],
        "blinkit": {"price": 125.0, "mrp": 140.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 119.0, "mrp": 140.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_09",
        "category": "staples",
        "title": "Fortune Sunlite Refined Sunflower Oil",
        "packSize": "1 L Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80",
        "tags": ["oil", "sunflower oil", "fortune", "cooking oil", "tel"],
        "blinkit": {"price": 135.0, "mrp": 150.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 130.0, "mrp": 150.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_10",
        "category": "staples",
        "title": "Saffola Gold Pro Healthy Lifestyle Oil",
        "packSize": "1 L Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80",
        "tags": ["saffola", "saffola gold", "cooking oil", "heart oil"],
        "blinkit": {"price": 165.0, "mrp": 185.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 158.0, "mrp": 185.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_11",
        "category": "staples",
        "title": "Fortune Premium Kachi Ghani Mustard Oil",
        "packSize": "1 L Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80",
        "tags": ["mustard oil", "sarson tel", "fortune", "kachi ghani"],
        "blinkit": {"price": 155.0, "mrp": 175.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 149.0, "mrp": 175.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_12",
        "category": "staples",
        "title": "Tata Salt Vacuum Evaporated Iodized Salt",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=300&auto=format&fit=crop&q=80",
        "tags": ["salt", "namak", "tata salt", "iodized", "staples"],
        "blinkit": {"price": 28.0, "mrp": 30.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 27.0, "mrp": 30.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_13",
        "category": "staples",
        "title": "Madhur Pure & Hygienic Sugar",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=300&auto=format&fit=crop&q=80",
        "tags": ["sugar", "cheeni", "madhur", "sweetener"],
        "blinkit": {"price": 54.0, "mrp": 60.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 52.0, "mrp": 60.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_staple_14",
        "category": "staples",
        "title": "Everest Turmeric Powder / Haldi",
        "packSize": "200 g Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=300&auto=format&fit=crop&q=80",
        "tags": ["haldi", "turmeric", "everest", "masala", "spices"],
        "blinkit": {"price": 48.0, "mrp": 55.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 45.0, "mrp": 55.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 7. CHOCOLATES & SWEETS (10 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_sweet_01",
        "category": "sweets",
        "title": "Cadbury Dairy Milk Silk Chocolate Bar",
        "packSize": "60 g",
        "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=300&auto=format&fit=crop&q=80",
        "tags": ["chocolate", "cadbury", "silk", "dairy milk", "sweets"],
        "blinkit": {"price": 80.0, "mrp": 85.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 76.0, "mrp": 85.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_02",
        "category": "sweets",
        "title": "Cadbury Dairy Milk Roasted Almond",
        "packSize": "36 g",
        "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=300&auto=format&fit=crop&q=80",
        "tags": ["chocolate", "dairy milk", "almond", "cadbury"],
        "blinkit": {"price": 45.0, "mrp": 50.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 42.0, "mrp": 50.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_03",
        "category": "sweets",
        "title": "Nestlé KitKat 4 Finger Chocolate Bar",
        "packSize": "38 g",
        "imageUrl": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=300&auto=format&fit=crop&q=80",
        "tags": ["kitkat", "chocolate", "nestle", "wafer", "sweet"],
        "blinkit": {"price": 30.0, "mrp": 30.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 28.0, "mrp": 30.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_04",
        "category": "sweets",
        "title": "Ferrero Rocher Premium Hazelnut Chocolates",
        "packSize": "Pack of 4 (50 g)",
        "imageUrl": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=300&auto=format&fit=crop&q=80",
        "tags": ["ferrero rocher", "chocolate", "hazelnut", "luxury chocolate"],
        "blinkit": {"price": 175.0, "mrp": 195.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 169.0, "mrp": 195.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_05",
        "category": "sweets",
        "title": "Amul Dark Chocolate 55% Rich Cocoa",
        "packSize": "150 g Bar",
        "imageUrl": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=300&auto=format&fit=crop&q=80",
        "tags": ["dark chocolate", "amul", "cocoa", "chocolate"],
        "blinkit": {"price": 115.0, "mrp": 125.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 109.0, "mrp": 125.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_06",
        "category": "sweets",
        "title": "Haldiram's Gulab Jamun Sweet Tin",
        "packSize": "1 kg Tin",
        "imageUrl": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300&auto=format&fit=crop&q=80",
        "tags": ["gulab jamun", "sweets", "haldiram", "mithai"],
        "blinkit": {"price": 240.0, "mrp": 270.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 229.0, "mrp": 270.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_07",
        "category": "sweets",
        "title": "Haldiram's Sponge Rasgulla Sweet Tin",
        "packSize": "1 kg Tin",
        "imageUrl": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300&auto=format&fit=crop&q=80",
        "tags": ["rasgulla", "haldiram", "sweets", "mithai"],
        "blinkit": {"price": 235.0, "mrp": 260.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 225.0, "mrp": 260.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_08",
        "category": "sweets",
        "title": "Kwality Walls Chocobar Ice Cream",
        "packSize": "60 ml Stick",
        "imageUrl": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=300&auto=format&fit=crop&q=80",
        "tags": ["chocobar", "ice cream", "kwality walls", "chocolate"],
        "blinkit": {"price": 25.0, "mrp": 25.0, "eta": "8 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 24.0, "mrp": 25.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_09",
        "category": "sweets",
        "title": "Amul Vanilla Magic Ice Cream Tub",
        "packSize": "1 L Tub",
        "imageUrl": "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=300&auto=format&fit=crop&q=80",
        "tags": ["vanilla", "ice cream", "amul", "tub", "dessert"],
        "blinkit": {"price": 145.0, "mrp": 160.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 139.0, "mrp": 160.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_sweet_10",
        "category": "sweets",
        "title": "Snickers Peanut Caramel Chocolate Bar",
        "packSize": "45 g Bar",
        "imageUrl": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=300&auto=format&fit=crop&q=80",
        "tags": ["snickers", "peanut", "chocolate", "caramel"],
        "blinkit": {"price": 45.0, "mrp": 50.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 42.0, "mrp": 50.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 8. TEA, COFFEE & HEALTH DRINKS (10 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_tea_01",
        "category": "tea_coffee",
        "title": "Tata Tea Gold Premium Black Tea",
        "packSize": "500 g Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80",
        "tags": ["tea", "chai", "tata tea", "gold", "beverages"],
        "blinkit": {"price": 290.0, "mrp": 320.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 282.0, "mrp": 320.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_02",
        "category": "tea_coffee",
        "title": "Brooke Bond Red Label Strong Tea",
        "packSize": "500 g Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80",
        "tags": ["red label", "tea", "chai", "brooke bond"],
        "blinkit": {"price": 280.0, "mrp": 310.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 272.0, "mrp": 310.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_03",
        "category": "tea_coffee",
        "title": "Brooke Bond Taj Mahal Premium Tea",
        "packSize": "250 g Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80",
        "tags": ["taj mahal", "tea", "chai", "premium tea"],
        "blinkit": {"price": 195.0, "mrp": 215.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 188.0, "mrp": 215.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_04",
        "category": "tea_coffee",
        "title": "Nescafe Classic 100% Pure Instant Coffee",
        "packSize": "50 g Glass Jar",
        "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80",
        "tags": ["coffee", "nescafe", "instant coffee", "classic"],
        "blinkit": {"price": 185.0, "mrp": 195.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 178.0, "mrp": 195.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_05",
        "category": "tea_coffee",
        "title": "Nescafe Classic Instant Coffee Jar",
        "packSize": "100 g Glass Jar",
        "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80",
        "tags": ["coffee", "nescafe", "100g", "instant coffee"],
        "blinkit": {"price": 360.0, "mrp": 385.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 349.0, "mrp": 385.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_06",
        "category": "tea_coffee",
        "title": "Bru Gold 100% Granulated Pure Coffee",
        "packSize": "50 g Glass Jar",
        "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80",
        "tags": ["bru gold", "coffee", "bru", "instant coffee"],
        "blinkit": {"price": 175.0, "mrp": 190.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 168.0, "mrp": 190.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_07",
        "category": "tea_coffee",
        "title": "Cadbury Bournvita Chocolate Nutrition Drink",
        "packSize": "500 g Refill Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=300&auto=format&fit=crop&q=80",
        "tags": ["bournvita", "health drink", "cadbury", "chocolate drink"],
        "blinkit": {"price": 240.0, "mrp": 265.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 232.0, "mrp": 265.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_08",
        "category": "tea_coffee",
        "title": "Horlicks Classic Malt Nutrition Drink",
        "packSize": "500 g Refill Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=300&auto=format&fit=crop&q=80",
        "tags": ["horlicks", "health drink", "malt", "nutrition"],
        "blinkit": {"price": 250.0, "mrp": 275.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 242.0, "mrp": 275.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_09",
        "category": "tea_coffee",
        "title": "Complan Royal Chocolate Health Drink",
        "packSize": "500 g Refill Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=300&auto=format&fit=crop&q=80",
        "tags": ["complan", "chocolate", "health drink", "growth"],
        "blinkit": {"price": 270.0, "mrp": 295.0, "eta": "13 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 262.0, "mrp": 295.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_tea_10",
        "category": "tea_coffee",
        "title": "Tetley Green Tea Lemon & Honey",
        "packSize": "25 Tea Bags",
        "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=80",
        "tags": ["green tea", "tetley", "lemon honey", "detox"],
        "blinkit": {"price": 180.0, "mrp": 200.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 172.0, "mrp": 200.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 9. CLEANING & HOUSEHOLD (10 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_clean_01",
        "category": "cleaning",
        "title": "Vim Lemon Dishwash Liquid Gel Bottle",
        "packSize": "500 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["vim", "dishwash", "liquid", "cleaning", "household"],
        "blinkit": {"price": 110.0, "mrp": 125.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 105.0, "mrp": 125.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_02",
        "category": "cleaning",
        "title": "Vim Dishwash Bar Soap Value Pack",
        "packSize": "300 g (Pack of 3)",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["vim bar", "dishwash soap", "cleaning"],
        "blinkit": {"price": 45.0, "mrp": 50.0, "eta": "9 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 42.0, "mrp": 50.0, "eta": "7 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_03",
        "category": "cleaning",
        "title": "Surf Excel Matic Top Load Liquid Detergent",
        "packSize": "1 L Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=300&auto=format&fit=crop&q=80",
        "tags": ["surf excel", "detergent", "laundry", "matic", "cleaning"],
        "blinkit": {"price": 220.0, "mrp": 240.0, "eta": "14 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 212.0, "mrp": 240.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_04",
        "category": "cleaning",
        "title": "Ariel Matic Front Load Detergent Powder",
        "packSize": "1 kg Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=300&auto=format&fit=crop&q=80",
        "tags": ["ariel", "detergent", "washing powder", "laundry"],
        "blinkit": {"price": 235.0, "mrp": 260.0, "eta": "13 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 228.0, "mrp": 260.0, "eta": "10 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_05",
        "category": "cleaning",
        "title": "Harpic Power Plus Disinfectant Toilet Cleaner",
        "packSize": "500 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["harpic", "toilet cleaner", "disinfectant", "bathroom"],
        "blinkit": {"price": 98.0, "mrp": 105.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 93.0, "mrp": 105.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_06",
        "category": "cleaning",
        "title": "Colin Glass & Multi-Surface Cleaner Spray",
        "packSize": "500 ml Spray",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["colin", "glass cleaner", "spray", "cleaning"],
        "blinkit": {"price": 105.0, "mrp": 115.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 99.0, "mrp": 115.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_07",
        "category": "cleaning",
        "title": "Dettol Antiseptic Disinfectant Liquid",
        "packSize": "550 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=300&auto=format&fit=crop&q=80",
        "tags": ["dettol", "antiseptic", "disinfectant", "first aid"],
        "blinkit": {"price": 205.0, "mrp": 225.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 198.0, "mrp": 225.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_08",
        "category": "cleaning",
        "title": "Scotch-Brite Cellulose Sponge Wipe",
        "packSize": "Pack of 3",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["scotch brite", "sponge wipe", "kitchen wipe", "cleaning"],
        "blinkit": {"price": 140.0, "mrp": 160.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 132.0, "mrp": 160.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_09",
        "category": "cleaning",
        "title": "Comfort After Wash Fabric Conditioner Lily",
        "packSize": "860 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=300&auto=format&fit=crop&q=80",
        "tags": ["comfort", "fabric conditioner", "laundry", "softener"],
        "blinkit": {"price": 230.0, "mrp": 255.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 220.0, "mrp": 255.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_clean_10",
        "category": "cleaning",
        "title": "Lizol Floral Disinfectant Floor Cleaner",
        "packSize": "500 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1585421514738-01798e348b17?w=300&auto=format&fit=crop&q=80",
        "tags": ["lizol", "floor cleaner", "disinfectant", "floral"],
        "blinkit": {"price": 95.0, "mrp": 105.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 89.0, "mrp": 105.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },

    # -------------------------------------------------------------------------
    # 10. PERSONAL CARE (12 Items)
    # -------------------------------------------------------------------------
    {
        "id": "prod_care_01",
        "category": "personal_care",
        "title": "Dettol Original Liquid Handwash Refill",
        "packSize": "675 ml Refill Pouch",
        "imageUrl": "https://images.unsplash.com/photo-1608248597359-593674681640?w=300&auto=format&fit=crop&q=80",
        "tags": ["dettol", "handwash", "soap", "hygiene", "personal care"],
        "blinkit": {"price": 95.0, "mrp": 109.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 90.0, "mrp": 109.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_02",
        "category": "personal_care",
        "title": "Lifebuoy Total 10 Antibacterial Soap Bar",
        "packSize": "Pack of 4 (400 g)",
        "imageUrl": "https://images.unsplash.com/photo-1607006314646-608a0d0d82aa?w=300&auto=format&fit=crop&q=80",
        "tags": ["lifebuoy", "soap", "bathing soap", "antibacterial"],
        "blinkit": {"price": 140.0, "mrp": 160.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 132.0, "mrp": 160.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_03",
        "category": "personal_care",
        "title": "Dettol Original Bathing Soap Bar",
        "packSize": "Pack of 4 (300 g)",
        "imageUrl": "https://images.unsplash.com/photo-1607006314646-608a0d0d82aa?w=300&auto=format&fit=crop&q=80",
        "tags": ["dettol soap", "soap", "bathing soap"],
        "blinkit": {"price": 150.0, "mrp": 170.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 144.0, "mrp": 170.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_04",
        "category": "personal_care",
        "title": "Colgate Strong Teeth Anticavity Toothpaste",
        "packSize": "150 g Tube",
        "imageUrl": "https://images.unsplash.com/photo-1559591937-e109d94943dc?w=300&auto=format&fit=crop&q=80",
        "tags": ["colgate", "toothpaste", "dental", "strong teeth"],
        "blinkit": {"price": 105.0, "mrp": 115.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 98.0, "mrp": 115.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_05",
        "category": "personal_care",
        "title": "Sensodyne Fresh Mint Sensitive Toothpaste",
        "packSize": "75 g Tube",
        "imageUrl": "https://images.unsplash.com/photo-1559591937-e109d94943dc?w=300&auto=format&fit=crop&q=80",
        "tags": ["sensodyne", "toothpaste", "sensitivity", "fresh mint"],
        "blinkit": {"price": 135.0, "mrp": 145.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 128.0, "mrp": 145.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_06",
        "category": "personal_care",
        "title": "Closeup Everfresh Red Hot Gel Toothpaste",
        "packSize": "150 g Tube",
        "imageUrl": "https://images.unsplash.com/photo-1559591937-e109d94943dc?w=300&auto=format&fit=crop&q=80",
        "tags": ["closeup", "toothpaste", "gel toothpaste", "red hot"],
        "blinkit": {"price": 110.0, "mrp": 120.0, "eta": "10 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 104.0, "mrp": 120.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_07",
        "category": "personal_care",
        "title": "Dove Daily Shine Damage Therapy Shampoo",
        "packSize": "340 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=300&auto=format&fit=crop&q=80",
        "tags": ["dove", "shampoo", "hair", "daily shine", "hair care"],
        "blinkit": {"price": 280.0, "mrp": 310.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 269.0, "mrp": 310.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_08",
        "category": "personal_care",
        "title": "Head & Shoulders Smooth & Silky Shampoo",
        "packSize": "340 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=300&auto=format&fit=crop&q=80",
        "tags": ["head and shoulders", "shampoo", "anti dandruff"],
        "blinkit": {"price": 290.0, "mrp": 325.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 279.0, "mrp": 325.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_09",
        "category": "personal_care",
        "title": "Pantene Advanced Hairfall Solution Shampoo",
        "packSize": "340 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=300&auto=format&fit=crop&q=80",
        "tags": ["pantene", "shampoo", "hairfall control"],
        "blinkit": {"price": 275.0, "mrp": 305.0, "eta": "12 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 265.0, "mrp": 305.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_10",
        "category": "personal_care",
        "title": "Nivea Soft Light Moisturizer Cream",
        "packSize": "100 ml Tub",
        "imageUrl": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&auto=format&fit=crop&q=80",
        "tags": ["nivea", "cream", "moisturizer", "skincare", "soft"],
        "blinkit": {"price": 180.0, "mrp": 210.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 169.0, "mrp": 210.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_11",
        "category": "personal_care",
        "title": "Vaseline Intensive Care Deep Moisture Lotion",
        "packSize": "200 ml Bottle",
        "imageUrl": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&auto=format&fit=crop&q=80",
        "tags": ["vaseline", "body lotion", "moisture", "skincare"],
        "blinkit": {"price": 195.0, "mrp": 225.0, "eta": "11 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 185.0, "mrp": 225.0, "eta": "8 mins", "deepLink": "https://zeptonow.com"},
    },
    {
        "id": "prod_care_12",
        "category": "personal_care",
        "title": "Gillette Mach3 Turbo Shaving Razor Cartridges",
        "packSize": "Pack of 4",
        "imageUrl": "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=300&auto=format&fit=crop&q=80",
        "tags": ["gillette", "mach3", "razor", "cartridge", "shaving", "grooming"],
        "blinkit": {"price": 490.0, "mrp": 549.0, "eta": "13 mins", "deepLink": "https://blinkit.com"},
        "zepto": {"price": 475.0, "mrp": 549.0, "eta": "9 mins", "deepLink": "https://zeptonow.com"},
    },
]

def search_catalog(query: str = "all", category: str = "all") -> List[Dict[str, Any]]:
    """
    Returns matched products from the master catalog.
    If query is 'all' or empty, returns all products in the specified category.
    """
    q = query.lower().strip()
    cat = category.lower().strip()

    filtered = MASTER_PRODUCTS

    # Filter by category if specified
    if cat and cat != "all":
        filtered = [p for p in filtered if p["category"] == cat]

    # If query is 'all' or '*' or empty, return all matching category items
    if not q or q in ("all", "*", "everything", "all products"):
        return filtered

    # Search keyword matching
    results = []
    for p in filtered:
        title = p["title"].lower()
        tags = [t.lower() for t in p.get("tags", [])]
        category_name = p["category"].lower()

        # Check direct substring or tag match
        if q in title or any(q in t for t in tags) or any(t in q for t in tags) or q in category_name:
            results.append(p)
        else:
            # Word token overlap match
            q_words = [w for w in q.split() if len(w) > 2]
            if any(w in title or any(w in t for t in tags) for w in q_words):
                results.append(p)

    return results if results else filtered[:12]
